# Nao subir Kafka automatico no dev mode: usamos os 2 brokers reais
quarkus.kafka.devservices.enabled=false


# ===================== MOCK PRODUCER (origem) =====================
mp.messaging.outgoing.gerador-entrada.connector=smallrye-kafka
mp.messaging.outgoing.gerador-entrada.bootstrap.servers=${KAFKA_ORIGEM_BOOTSTRAP:localhost:9092}
mp.messaging.outgoing.gerador-entrada.topic=${KAFKA_ORIGEM_TOPICO:sispm.posicional.entrada}
mp.messaging.outgoing.gerador-entrada.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# ===================== BROKER DE ORIGEM (consome posicional) =====================
mp.messaging.incoming.entrada.connector=smallrye-kafka
mp.messaging.incoming.entrada.bootstrap.servers=${KAFKA_ORIGEM_BOOTSTRAP:localhost:9092}
mp.messaging.incoming.entrada.topic=${KAFKA_ORIGEM_TOPICO:sispm.posicional.entrada}
mp.messaging.incoming.entrada.group.id=${KAFKA_ORIGEM_GROUP:anticorruption}
mp.messaging.incoming.entrada.auto.offset.reset=earliest
mp.messaging.incoming.entrada.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
# Mensagem invalida (layout quebrado) vai para DLQ no broker de origem
mp.messaging.incoming.entrada.failure-strategy=dead-letter-queue
mp.messaging.incoming.entrada.dead-letter-queue.topic=${KAFKA_ORIGEM_DLQ:sispm.posicional.dlq}

# ===================== BROKER DE DESTINO (publica JSON) =====================
mp.messaging.outgoing.saida.connector=smallrye-kafka
mp.messaging.outgoing.saida.bootstrap.servers=${KAFKA_DESTINO_BOOTSTRAP:localhost:9093}
mp.messaging.outgoing.saida.topic=${KAFKA_DESTINO_TOPICO:sispm.json.saida}
mp.messaging.outgoing.saida.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.saida.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.saida.acks=all

# Se os brokers exigirem SASL/SSL, adicione por canal, ex.:
# mp.messaging.incoming.entrada.security.protocol=SASL_SSL
# mp.messaging.incoming.entrada.sasl.mechanism=PLAIN
# mp.messaging.incoming.entrada.sasl.jaas.config=...
# (idem para mp.messaging.outgoing.saida.*)
